#ifndef ENUM
#define ENUM

enum {ORADEA, ZERIND, ARAD, TIMISOARA, LUGOJ,
      MEHADIA, DROBETA,SIBIU, RVILCEA, CRAIOVA,
      FAGARAS, PITESTI, BUCHAREST, GIURGIU, URZICENI,
      VASLUI, IASI, NEAMT, HIRSOVA, EFORIE, TAM_MAPA
};

#endif // ENUM

